# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'src/templates'),
        ('static', 'src/static'),
        ('../config', 'config'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'engineio.async_drivers.asgi',
        'fastapi',
        'starlette',
        'pydantic',
        'jinja2',
        'src.main',
        'src.web',
        'src.drive_client',
        'src.tr_handler',
        'src.sync_logic',
        'src.utils',
        'src.config_manager',
        'webview',
        'objc',
        'Foundation',
        'AppKit',
        'WebKit',
        'InquirerPy',
        'InquirerPy.base',
        'InquirerPy.prompts',
        'prompt_toolkit',
        'prompt_toolkit.styles',
        'wcwidth',
        'multipart'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='TradeSync',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='TradeSync',
)
app = BUNDLE(
    coll,
    name='TradeSync.app',
    icon='static/TradeSync.icns',
    bundle_identifier='com.tommasotaffi.tradesync',
    version='0.2.0',
)
